CREATE TABLE "users_user_assigned_assistants" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "from_user_id" bigint NOT NULL, 
    "to_user_id" bigint NOT NULL
);

ALTER TABLE "users_user_assigned_assistants" ADD CONSTRAINT "users_user_assigned_assi_from_user_id_to_user_id_1f803a3f_uniq" UNIQUE ("from_user_id", "to_user_id");
ALTER TABLE "users_user_assigned_assistants" ADD CONSTRAINT "users_user_assigned__from_user_id_893e8f36_fk_users_use" FOREIGN KEY ("from_user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "users_user_assigned_assistants" ADD CONSTRAINT "users_user_assigned__to_user_id_529459c7_fk_users_use" FOREIGN KEY ("to_user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "users_user_assigned_assistants_from_user_id_893e8f36" ON "users_user_assigned_assistants" ("from_user_id");
CREATE INDEX "users_user_assigned_assistants_to_user_id_529459c7" ON "users_user_assigned_assistants" ("to_user_id");
