# Generated by Django 4.2.30 on 2026-04-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.AddField(
            model_name='consultation',
            name='appointment_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='ai_result',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='medical_notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='scanner_image_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_info',
            field=models.CharField(max_length=200),
        ),
    ]
